`MacosPopupButton` (closes #176)
macosui/macos_ui pull request #177
Opened 2022-01-19 09:34 UTC by whiplashoo

## Adds a new `MacosPopupButton` widget, trying to replicate the [Pop-Up button](https://developer.apple.com/design/human-interface-guidelines/macos/buttons/pop-up-buttons/) component from Apple's Guidelines.

**Final result:**

| Dark Theme                                 | Light Theme                                |
| ------------------------------------------ | ------------------------------------------ |
| <img src="https://imgur.com/ov0kzJC.jpg"/> | <img src="https://imgur.com/buhYEo1.jpg"/> |
| <img src="https://imgur.com/BOEH59L.jpg"/> | <img src="https://imgur.com/61S7DSX.jpg"/> |
| <img src="https://imgur.com/zY0d8RF.jpg"/> | <img src="https://imgur.com/W4CMa5z.jpg"/> |

**Screencast:** 

https://user-images.githubusercontent.com/9117427/150102681-488c3531-791f-4de3-8613-c3cc675d97ce.mov

**Based on Flutter's Material `DropdownButton` widget, but with these modifications:**

- Different size, padding, border shadows, animations, etc., trying to match Apple design as much as possible. All these were eye-balled from pop-up buttons found in System Preferences.
- Double caret icon at the right edge of the button (done with a `CustomPainter`).
- macOS-themed styling.
- No scrollbar when menu is open.
- An up or down caret symbol for when the menu has items that cannot fit the available constraints (i.e. with a longer items list).

User can also navigate the open menu with up/down arrow keys and select an item with the Return key.

Future development can include:

- Translucency effect for the open menu.
- More tests (especially for its visual design).

## Pre-launch Checklist

- [✅] I have run `dartfmt` on all changed files 
- [✅] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [✅] I have added/updated relevant documentation 
- [✅] I have run "optimize/organize imports" on all changed files
- [✅] I have addressed all analyzer warnings as best I could

2022-01-20 20:54 UTC, whiplashoo commented
Should close #176 .

2022-02-26 16:14 UTC, GroovinChip commented
Hello, @whiplashoo! Thank you so much for your PR, it looks amazing! I am gearing up to start working on this project again in the near future, and I see that this PR is failing some checks. Would you mind addressing that before I review, please? Cheers!

2022-03-04 17:12 UTC, GroovinChip commented
@whiplashoo what are your thoughts on adding `MacosPopupButtonTheme` and `MacosPopupButtonThemeData` classes? This way users can set a default theme at the root level, or for specific widget trees.

2022-03-04 17:15 UTC, GroovinChip commented
Also, does this PR contain your work from #171 ? If so then we can close that PR in favor of this one.

2022-03-04 17:38 UTC, whiplashoo commented
@GroovinChip 

- No, it doesn't contain work from #171, they are separate branches.
- Yes, I can see how a `MacosPopupButtonTheme` could be useful. I guess it should be implemented in a similar logic like `PushButtonThemeData`, for example?

2022-03-04 19:39 UTC, GroovinChip commented
> @whiplashoo 
> 
> * Yes, I can see how a `MacosPopupButtonTheme` could be useful. I guess it should be implemented in a similar logic like `PushButtonThemeData`, for example?

Yep, exactly

2022-03-06 18:19 UTC, GroovinChip requested changes
Looks great. Let's just get the Theme classes implemented and then we'll be good to go.

2022-03-06 18:19 UTC, GroovinChip commented on example/macos/Podfile.lock
> +COCOAPODS: 1.10.2
```suggestion
COCOAPODS: 1.11.2
```

2022-03-07 08:54 UTC, whiplashoo commented
In trying to implement the theme classes, I tried to use as a starting point the `PushButtonTheme` classes. 

I noticed, however, that this won't work (i.e. the color of the `PushButtons` is not yellow):

```dart
...
return MacosApp(
    title: 'macos_ui example',
    theme: MacosThemeData.light().copyWith(
      pushButtonTheme: const PushButtonThemeData( 
        color: Colors.yellow,
        disabledColor: Colors.blue,
        secondaryColor: Colors.red,
      ),
    ),
...
```

Using `PushButtonThemeData().copyWith()` doesn't help either. Isn't this the way it's expected for users to override theme colors? 

I found that in the copyWith method of `MacosThemeData`, the user-provided parameters [are not passed](https://github.com/whiplashoo/macos_ui/blob/0bf7ded8618b4d6d80d2cd07041f4124b5b3acda/lib/src/theme/macos_theme.dart#L402-L404) when constructing the `MacosThemeData`. Doing this for other `MacosThemeData` properties like `primaryColor`, `canvasColor`, etc. works properly. 

I guess this needs to be fixed first? Would be willing to tackle this on a separate issue.

2022-03-07 14:06 UTC, GroovinChip commented
> In trying to implement the theme classes, I tried to use as a starting point the `PushButtonTheme` classes.
> 
> I noticed, however, that this won't work (i.e. the color of the `PushButtons` is not yellow):
> 
> ```dart
> ...
> return MacosApp(
>     title: 'macos_ui example',
>     theme: MacosThemeData.light().copyWith(
>       pushButtonTheme: const PushButtonThemeData( 
>         color: Colors.yellow,
>         disabledColor: Colors.blue,
>         secondaryColor: Colors.red,
>       ),
>     ),
> ...
> ```
> 
> Using `PushButtonThemeData().copyWith()` doesn't help either. Isn't this the way it's expected for users to override theme colors?
> 
> I found that in the copyWith method of `MacosThemeData`, the user-provided parameters [are not passed](https://github.com/whiplashoo/macos_ui/blob/0bf7ded8618b4d6d80d2cd07041f4124b5b3acda/lib/src/theme/macos_theme.dart#L402-L404) when constructing the `MacosThemeData`. Doing this for other `MacosThemeData` properties like `primaryColor`, `canvasColor`, etc. works properly.
> 
> I guess this needs to be fixed first? Would be willing to tackle this on a separate issue.

Oof. Yes, this looks like a bug

2022-03-08 07:56 UTC, whiplashoo commented
Added `MacosPopupButtonTheme` and `MacosPopupButtonThemeData` classes, so user can theme `MacosPopupButton`s from the root of the app (or per widget tree).

The customizable settings are `highlightColor`, `backgroundColor`, `popupColor`. 

For a visual example, setting these colors:

```dart
return MacosApp(
  title: 'macos_ui example',
  theme: MacosThemeData.light().copyWith(
    macosPopupButtonTheme: const MacosPopupButtonThemeData(
      highlightColor: MacosColors.appleOrange,
      backgroundColor: MacosColors.appleGreen,
      popupColor: MacosColors.systemTealColor,
    ),
  ),
```

results to this `MacosPopupButton` style:

<p>
<img width="45%" alt="Screenshot 2022-03-08 at 9 44 43 AM" src="https://user-images.githubusercontent.com/9117427/157191507-c251bc25-f742-42db-9f0f-6e756db68e3a.png">

<img width="45%" alt="Screenshot 2022-03-08 at 9 44 53 AM" src="https://user-images.githubusercontent.com/9117427/157191504-f56ccdc9-181e-4493-b54f-770ff8422bef.png">
</p>

I will also open an issue to fix the bug with the other widget theme classes.

2022-03-08 16:13 UTC, GroovinChip approved these changes
LGTM. I will commit the changes requested, deal with merge conflicts, and merge.

2022-03-08 16:13 UTC, GroovinChip commented on lib/src/buttons/popup_button.dart
> +  /// Create a [MacosPopupButtonTheme].
```suggestion
  /// Creates a [MacosPopupButtonTheme].
```

2022-03-08 16:13 UTC, GroovinChip commented on lib/src/buttons/popup_button.dart
> +/// [MacosPopupButton]s when it's used with [MacosPopupButtonTheme] or with the
```suggestion
/// [MacosPopupButton]s when it is used with [MacosPopupButtonTheme] or with the
```

2022-03-08 16:13 UTC, GroovinChip commented on lib/src/buttons/popup_button.dart
> +  /// Sets the color of the caret icons and the color of a [MacosPopupMenuItem]s' background when the mouse hovers over it.
```suggestion
  /// Sets the color of the caret icons and the color of a [MacosPopupMenuItem]'s background when the mouse hovers over it.
```

2022-03-08 16:13 UTC, GroovinChip commented on lib/src/buttons/popup_button.dart
> +  /// Linearly interpolate between two [MacosPopupButtonThemeData].
```suggestion
  /// Linearly interpolates between two [MacosPopupButtonThemeData].
```

2022-03-08 16:15 UTC, GroovinChip commented on pubspec.yaml
> +version: 0.11.0
```suggestion
version: 0.12.0
```

2022-03-08 16:16 UTC, GroovinChip commented
Waiting on checks to complete before merging.

2022-03-08 16:20 UTC, merged