fix: Sidebar and ResizablePane more closely track native MacOS behavior
macosui/macos_ui pull request #178
Opened 2022-01-19 22:32 UTC by jmatth

In native applications, resizing the sidebar or a split view tracks the horizontal coordinates of the cursor. Currently in `macos_ui`, resizing is done based on the drag delta on each frame. This leads to what is probably a bug where if you drag past the min or max width and then back, the elements will continue to resize even though your cursor is no longer near the divider. Here's a recording of the current behavior to illustrate:

https://user-images.githubusercontent.com/1316184/150221976-719fbc29-9621-4842-a5c5-5e1fa0d0de28.mov

Also in most native apps, dragging the sidebar far enough to the left will cause it to instantly close, rather than just stop at its minimum width. I implemented this behavior, along with a flag to disable it if desired.

Here's a recording showing the updated behavior from this PR:

https://user-images.githubusercontent.com/1316184/150222338-b83a1dba-3897-419e-befd-f3248df701d5.mov

## Pre-launch Checklist

- [x] I have run `dartfmt` on all changed files 
- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [x] I have added/updated relevant documentation 
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could

2022-01-25 19:32 UTC, cadenkriese commented
It looks like macOS or at least finder has some more complex snapping behavior around the minimum widths. I also noticed the haptics in my trackpad going whenever there was a snap as a minor detail.

https://user-images.githubusercontent.com/13630061/151046455-8429681a-13b1-4de7-b04b-77cccf258d99.mp4

2022-01-26 15:35 UTC, jmatth commented
Oh wow, never noticed that before. I'm seeing the following behavior on my machine:

1. There's a particular width the sidebar will snap to when you drag close enough. This snapping is accompanied by haptic feedback from the force touch trackpad
2. Dragging past that point allows you to continue shrinking the sidebar
3. The sidebar stops shrinking entirely at a particular minimum width but does not immediately jump to being closed
4. Once the mouse cursor passes some other invisible cutoff, the sidebar snaps closed

I'm only observing this behavior in the Finder app. Other built-in and 3rd party native applications I tested either have the behavior I implemented here, with some also including the functionality from point 3 above.

Everything but the haptic feedback should be easy enough to add via optional params. Unfortunately I don't see an easy way to add the haptic feedback, as [HapticFeedback](https://api.flutter.dev/flutter/services/HapticFeedback-class.html) only supports iOS and Android right now. It might be possible to make it work via a plugin that provides the appropriate platform channels for MacOS but I don't have any experience with that.

2022-03-06 18:03 UTC, GroovinChip commented on CHANGELOG.md
> +*
```suggestion

```

2022-03-06 18:03 UTC, GroovinChip commented on CHANGELOG.md
> +* Sidebar and ResizeablePane more precicely track cursor location
```suggestion
* Sidebar and ResizablePane more precisely track cursor location
```

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/resizable_pane.dart
> +      onHorizontalDragStart: (_) {
Please add a test for this behavior

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/resizable_pane.dart
> +          final newWidth = _resizeOnRight
Please add a test for this behavior

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/sidebar.dart
> +  }) : dragClosedBuffer = dragClosedBuffer ?? minWidth / 2;
Please add a test for this behavior

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/sidebar.dart
> +  /// dragged to trigger this behavior. Defaults to true.
```suggestion
  /// dragged to trigger this behavior. 
  /// 
  /// Defaults to `true`.
```

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/sidebar.dart
> +  /// below [minWidth].  Defaults to half of [minWidth]. Set to 0 to cause the
```suggestion
  /// below [minWidth]. Defaults to half of [minWidth]. Set to `0` to cause the
```

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/window.dart
> +                  onHorizontalDragStart: (_) {
Please add a test for this behavior

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/window.dart
> +                    final sidebar = widget.sidebar!;
Please add a test for this behavior

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/window.dart
> +                          _sidebarDragStartWidth + details.localPosition.dx;
Please add a test for this behavior

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/window.dart
> +                        newWidth = sidebar.startWidth!;
Please add a test for this behavior

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/window.dart
> +                      if (sidebar.dragClosed) {
Please add a test for this behavior

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/window.dart
> +                        _showSidebar = newWidth >= closeBelow;
Please add a test for this behavior

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/window.dart
> +                        sidebar.minWidth,
Please add a test for this behavior

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/window.dart
> +                          math.min(sidebar.maxWidth!, width),
Please add a test for this behavior

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/window.dart
> +                      if (_sidebarWidth == sidebar.minWidth)
Please add a test for this behavior

2022-03-06 18:03 UTC, GroovinChip commented on lib/src/layout/window.dart
> +                      else if (_sidebarWidth == sidebar.maxWidth)
Please add a test for this behavior

2022-03-08 16:18 UTC, GroovinChip commented on test/layout/window_test.dart
> +      final backgroundFinder = find.byType(AnimatedPositioned).at(1);
@jmatth are you doing anything with these finders in your test? Simply finding them by type is not really a test. Or is your work on improving the tests not complete yet?

2022-03-08 16:20 UTC, GroovinChip commented on CHANGELOG.md
> +## [0.10.3]
```suggestion
## [0.12.1]
```

2022-03-08 16:20 UTC, GroovinChip commented on CHANGELOG.md
> +## [0.10.3]
Need to change this in `pubspec.yaml` as well.

2022-03-08 16:50 UTC, jmatth commented on test/layout/window_test.dart
> +      final backgroundFinder = find.byType(AnimatedPositioned).at(1);
They're used in like every test in that file:

```bash
$ rg resizerFinder window_test.dart
42:      final resizerFinder = find.byType(AnimatedPositioned).at(3);
83:        await tester.drag(resizerFinder, const Offset(safeDelta, 0));
92:        await tester.drag(resizerFinder, const Offset(overflowDelta, 0));
102:            await tester.startGesture(tester.getCenter(resizerFinder));
114:        await tester.drag(resizerFinder, const Offset(-safeDelta, 0));
129:              resizerFinder,
145:            await tester.drag(resizerFinder, const Offset(-overflowDelta, 0));
158:                await tester.startGesture(tester.getCenter(resizerFinder));
182:              await tester.startGesture(tester.getCenter(resizerFinder));
198:            await tester.drag(resizerFinder, const Offset(-overflowDelta, 0));
209:              await tester.startGesture(tester.getCenter(resizerFinder));
233:                await tester.startGesture(tester.getCenter(resizerFinder));
259:            await tester.drag(resizerFinder, Offset(snapToStartBuffer * 2, 0));
268:              resizerFinder,
```

`sidebarFinder` and `backgroundFinder` are both called from inside the helper `expectSidebarOpen`, which is then used in every test:

```bash
$ rg expectSidebarOpen window_test.dart
45:      final expectSidebarOpen = (tester, {required double width}) {
72:        expectSidebarOpen(tester, width: startWidth);
86:        expectSidebarOpen(tester, width: startWidth + safeDelta);
95:        expectSidebarOpen(tester, width: maxWidth);
108:        expectSidebarOpen(tester, width: maxWidth);
117:        expectSidebarOpen(tester, width: startWidth - safeDelta);
137:            expectSidebarOpen(tester, width: minWidth);
174:            expectSidebarOpen(tester, width: startWidth - safeDelta);
201:            expectSidebarOpen(tester, width: minWidth);
215:          expectSidebarOpen(tester, width: minWidth);
237:            expectSidebarOpen(tester, width: startWidth);
242:            expectSidebarOpen(
262:            expectSidebarOpen(
272:            expectSidebarOpen(tester, width: startWidth);
```

2022-03-10 14:17 UTC, GroovinChip commented
@jmatth can you address the package analysis check please? I can re-review after that.

2022-03-10 14:52 UTC, jmatth commented
Heh, that `new` keyword it's complaining about is in a docstring in a file I didn't even modify. The Flutter `stable` channel probably updated its default analysis rules. But whatever, fixed it @GroovinChip

2022-03-10 17:27 UTC, GroovinChip requested changes
@jmatth  everything looks good, there's just one thing left to do - update the version in `pubspec.yaml` to match the version in `CHANGELOG.md`.

2022-03-10 20:35 UTC, GroovinChip approved these changes
LGTM, waiting on checks

2022-03-10 21:38 UTC, merged