Implemented Switch
macosui/macos_ui pull request #21
Opened 2021-04-14 23:51 UTC by bdlukaa

- MacosTheme.maybeOf now can return a nullable value
- Added Switch to Example app

2021-04-14 23:55 UTC, GroovinChip commented
Looks great! Let's bump the version to `0.0.3`, add to the changelog, and update the readme before merging.

2021-04-14 23:56 UTC, GroovinChip commented
Hit the wrong button 😅

2021-04-14 23:59 UTC, GroovinChip requested changes
Bump version, update changelog and readme

2021-04-15 00:00 UTC, bdlukaa commented
Done

2021-04-15 00:02 UTC, GroovinChip approved these changes
I can do the readme later

2021-04-15 00:02 UTC, merged