Implemented RadioButton
macosui/macos_ui pull request #27
Opened 2021-04-15 21:19 UTC by bdlukaa

![](https://developer.apple.com/design/human-interface-guidelines/macos/images/radioButtons.png)

2021-04-17 16:11 UTC, GroovinChip commented
@bdlukaa pull the latest changes from dev

2021-04-17 16:12 UTC, GroovinChip commented
@bdlukaa pull the latest changes from dev

2021-04-17 23:39 UTC, GroovinChip requested changes

2021-04-17 23:39 UTC, GroovinChip commented on CHANGELOG.md
> +* Implemented `RadioButton`
Place under a new version, or group all 3 new widgets under a new version

2021-04-17 23:39 UTC, GroovinChip commented on lib/src/buttons/radio_button.dart
> +                      context.maybeStyle?.primaryColor ??
There is no `maybeStyle` any more.

2021-04-17 23:42 UTC, GroovinChip commented
Ensure `dartfmt` and optimize imports have been run on all changed files in addition to other requested changes.

2021-04-18 00:48 UTC, bdlukaa commented on lib/src/buttons/radio_button.dart
> +                      context.maybeStyle?.primaryColor ??
Done

2021-04-18 00:49 UTC, bdlukaa commented on CHANGELOG.md
> +* Implemented `RadioButton`
Done

2021-04-18 14:32 UTC, GroovinChip requested changes
Ensure unselected color is correct in light theme

Current:
<img width="165" alt="Screen Shot 2021-04-18 at 10 31 39 AM" src="https://user-images.githubusercontent.com/4250470/115149293-64ce1080-a031-11eb-9e96-fc96c21ad7c7.png">

Spec:
<img width="165" alt="Screen Shot 2021-04-18 at 10 31 49 AM" src="https://user-images.githubusercontent.com/4250470/115149298-6bf51e80-a031-11eb-8dd1-970d636f5a83.png">
<img width="221" alt="Screen Shot 2021-04-18 at 10 32 01 AM" src="https://user-images.githubusercontent.com/4250470/115149300-6dbee200-a031-11eb-81ac-3534a13ef878.png">

2021-04-19 00:31 UTC, GroovinChip requested changes
See review comments on #24 about merging PR's for easier conflict resolution

2021-04-19 15:17 UTC, bdlukaa commented
Closing as duplicate of https://github.com/GroovinChip/macos_ui/pull/47

2021-04-19 15:17 UTC, closed without merging