Tab view padding
macosui/macos_ui pull request #285
Opened 2022-07-22 07:58 UTC by stMerlHin

I add padding parameter to MacosTabView to allow setting custom.
I am using macos_ui package in one of my apps and the default padding impact the ui.
here is a screenshot of the app with the MacosTabView with the default padding and a DataTable as one of children
![MacosTabView with default padding](https://user-images.githubusercontent.com/77164238/180391210-d7bf2db8-dc2f-4f41-8c7f-3c588760026b.png)

And here is the same app with custom padding

 
![MacosTabView](https://user-images.githubusercontent.com/77164238/180390042-dba20ba6-c0d6-4e6b-a3ff-fcce8988db72.png)

## Pre-launch Checklist

- [x] I have run `dartfmt` on all changed files 
- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [x] I have added/updated relevant documentation 
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could

2022-07-27 20:40 UTC, GroovinChip requested changes, later dismissed
Thanks for contributing! Please pull the latest from `dev` and make the requested changes.

2022-07-27 20:40 UTC, GroovinChip commented on CHANGELOG.md
> +## [1.7.0+1]
```suggestion
## [1.7.2]
```

The latest version is now 1.7.1, so 1.7.2 is an appropriate change

2022-07-27 20:40 UTC, GroovinChip commented on lib/src/layout/tab_view/tab_view.dart
> +  ///The padding of the tab view widget
```suggestion
  /// The padding of the tab view widget.
  ///
  /// Defaults to `EdgeInsets.all(12.0)`.
```

2022-07-27 20:40 UTC, GroovinChip commented on pubspec.yaml
> +version: 1.7.0+1
```suggestion
version: 1.7.2
```

2022-08-11 16:21 UTC, stMerlHin commented
Have made all changes.

2022-08-14 14:11 UTC, GroovinChip approved these changes
LGTM! Thanks so much for your contribution, @stMerlHin!

2022-08-14 14:15 UTC, merged

2022-08-16 09:15 UTC, stMerlHin commented
Very pleased to do such a little thing. Realy love your work.