Implemented Level indicator
macosui/macos_ui pull request #30
Opened 2021-04-16 16:44 UTC by bdlukaa

* Continuous capacity indicator ![](https://developer.apple.com/design/human-interface-guidelines/macos/images/indicators-continous.png)
* Discrete capacity indicator ![](https://developer.apple.com/design/human-interface-guidelines/macos/images/indicators-discrete.png)
* Rating indicator ![](https://developer.apple.com/design/human-interface-guidelines/macos/images/indicator-rating.png)
* Relevance indicator ![](https://developer.apple.com/design/human-interface-guidelines/macos/images/indicator-relevance.png)

2021-04-17 23:41 UTC, GroovinChip requested changes
Ensure `dartfmt` and optimize imports have been run on all changed files in addition to other requested changes.

2021-04-17 23:41 UTC, GroovinChip commented on lib/src/indicators/rating_indicator.dart
> +                context.maybeStyle?.primaryColor ??
There is no more `maybeStyle`

2021-04-18 00:45 UTC, bdlukaa commented on lib/src/indicators/rating_indicator.dart
> +                context.maybeStyle?.primaryColor ??
Done

2021-04-18 14:41 UTC, GroovinChip requested changes
Track colors for CapacityIndicators and RelevanceIndicator are not correct for light theme
<img width="992" alt="Screen Shot 2021-04-18 at 10 39 33 AM" src="https://user-images.githubusercontent.com/4250470/115149540-9f847880-a032-11eb-885d-55eca2af7686.png">

2021-04-18 18:17 UTC, bdlukaa commented
@GroovinChip This is actually an issue with the `MacosTheme`. `CupertinoDynamicColor.resolveFrom` uses `CupertinoTheme.maybeBrightnessOf(context)`, that uses `MediaQuery.maybeOf(context)?.platformBrightness` for color fallback. A `CupertinoTheme` should be provided by the `MacosTheme` with the brightness, otherwise all the widgets that uses `CupertinoDynamicColor.resolve()` will use the device's brightness instead of the one provided in `MacosTheme`.

2021-04-18 19:32 UTC, GroovinChip commented
> @GroovinChip This is actually an issue with the `MacosTheme`. `CupertinoDynamicColor.resolveFrom` uses `CupertinoTheme.maybeBrightnessOf(context)`, that uses `MediaQuery.maybeOf(context)?.platformBrightness` for color fallback. A `CupertinoTheme` should be provided by the `MacosTheme` with the brightness, otherwise all the widgets that uses `CupertinoDynamicColor.resolve()` will use the device's brightness instead of the one provided in `MacosTheme`.

I think this will be resolved bu #43

2021-04-19 00:27 UTC, GroovinChip approved these changes
LGTM

2021-04-19 00:27 UTC, merged