feat: implement MacosTable
macosui/macos_ui pull request #320
Opened 2022-11-18 13:24 UTC by pithuene

I implemented a `MacosTable` widget which looks similar to the macOS `NSTableView`.
The table features ordering by column and row selection.
I have also added some tests for the basic operations.
I am sure there is still a lot to improve, both in code and in UI, but I hope this can serve as a starting point.

This is a screenshot of the table widget running in a process monitor application I am building.
Note that this is running on linux and the font is not the one used on macOS.
![Screenshot_2022-11-18_14-13-43](https://user-images.githubusercontent.com/21110295/202714510-e1898511-51ae-48fd-97db-f3182a07b132.png)

## Pre-launch Checklist

- [x] I have run `dartfmt` on all changed files 
- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [ ] I have added/updated relevant documentation 
- [ ] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could

2023-01-09 12:32 UTC, Yetispapa commented
This is awesome! @GroovinChip, is there something in the way for merging?

2023-01-11 12:56 UTC, stMerlHin commented
Beautiful, can't wait to see it in the new release.

2023-01-11 12:56 UTC, stMerlHin commented
Beautiful, can't wait to see it in the new release.

2023-01-13 19:15 UTC, GroovinChip requested changes
Hello @pithuene, and thank you for this PR! I'm excited to see a new widget being added, especially this one! 

Please review the feedback I've left and implement the requested changes. Additionally, please update the `CHANGELOG.md` file.

Thanks!

2023-01-13 19:15 UTC, GroovinChip commented on lib/macos_ui.dart
> +export 'src/table/macos_table.dart';
I believe a better location for this would be under `/layout`, since it's categorized under "Layout and organization" on the Human Interface Guidelines.

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_columns.dart
> +  final Widget Function(BuildContext, T) cellBuilder;
Please add documentation for all this

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_datasource.dart
> +  /// the key is how the table knows which row was selected.
If you could rewrite this without the use of "you", that would be great - something along the lines of "The key allows the table to know which row has been selected". It's descriptive without addressing the reader directly.

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_datasource.dart
> +  /// ValueKey of the index.
Avoid addressing the reader directly

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_datasource.dart
> +  // By what column and in what direction the table is ordered.
```suggestion
  /// The order and direction with which the table can be sorted.
```

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_datasource.dart
> +  MacosTableOrder<T>? order;
Change this to `tableOrder`.

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_datasource.dart
> +  // Callback to update the row count.
```suggestion
  /// Callback to update the row count.
```

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_datasource.dart
> +  /// You need to maintain some order from index (between 0 and rowCount)
```suggestion
  /// The main function through which data is fed into the table.
  ///
  /// You need to maintain some order from index (between 0 and rowCount).
```
Also, can you please explain what you mean by `You need to maintain some order from index (between 0 and rowCount)`?

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_datasource.dart
> +  final bool Function(MacosTableOrder<T>?)? changeOrder;
Rename to `changeTableOrder`

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_datasource.dart
> +  MacosTableSelection? _selection;
Rename to `_tableSelection`.

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_header.dart
> +  final MacosTableOrder<T>? order;
Please add documentation.

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_header.dart
> +  final List<ColumnDefinition<T>> colDefs;
Please rename to `columnDefinitions`.

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_order.dart
> +  void reverseDirection() {
Please add documentation.

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_row.dart
> +  final bool hasEvenRowHighlight;
Please add documentation.

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_row.dart
> +  final List<ColumnDefinition<T>> colDefs;
Please rename to `columnDefinitions`.

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_selection.dart
> +  final MacosTableSelection? newSelection;
Please add documentation.

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_view.dart
> +/// A scrollable data table with sorting and selection.
Please add some more detail to the documentation here. Use the Human Interface Guidelines if you need ideas.

Additionally, please turn this doc into a template and use the macro on the constructor.

2023-01-13 19:15 UTC, GroovinChip commented on lib/src/table/macos_table_view.dart
> +  final MacosTableDataSource<T> dataSource;
Please add documentation.

2023-01-16 18:51 UTC, pithuene commented
Hey @GroovinChip, thanks a lot for giving me feedback on my pull request!
I tried to implement your requested changes but am not sure what you were asking for in the changelog file.

Thanks again for your time!

2023-01-24 08:31 UTC, GroovinChip commented
> Hey @GroovinChip, thanks a lot for giving me feedback on my pull request! I tried to implement your requested changes but am not sure what you were asking for in the changelog file.
> 
> Thanks again for your time!

I mean add an entry that describes what the new version adds or changes. If you look at the file you'll understand.

2023-01-24 09:04 UTC, GroovinChip requested changes

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_columns.dart
> +  /// Usually either a [FlexColumnWidth] or a [FixedColumnWidth].
```suggestion
  /// The width of this column.
  ///
  /// Usually either a [FlexColumnWidth] or a [FixedColumnWidth].
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_columns.dart
> +  /// Receives the current [BuildContext] and the row value.
```suggestion
  /// The builder that creates the content of a cell.
  ///
  /// Receives the current [BuildContext] and the row value.
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_datasource.dart
> +  /// Limits with which indices `getRow` is called.
```suggestion
  /// The number of rows in the table.
  ///
  /// Limits with which indices `getRow` is called.
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_datasource.dart
> +  /// if you don't call this function, the new data may not be shown.
```suggestion
  /// Must be called after every data change. If it is not called, 
  /// the updated data may not be shown.
  ///
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_datasource.dart
> +  /// would also suffice.
```suggestion
  ///
  /// Even if the order is never changed, a [ValueKey] of the index
  /// would also suffice.
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_header.dart
> +  const MacosTableHeader({
Please add documentation here

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_header.dart
> +  final Function(ColumnDefinition<T>)? columnHeaderClicked;
Please add documentation here

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_row.dart
> +/// A widget to display a single row inside a [MacosTable].
```suggestion
/// {@template macosTableRow} 
/// A widget to display a single row inside a [MacosTable].
/// {@endtemplate}
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_row.dart
> +  const MacosTableRow({
```suggestion
  /// {@macro macosTableRow}
  const MacosTableRow({
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_row.dart
> +  /// The same information is also contained in the [columnDefinitions],
```suggestion
  /// A map from column index to its [TableColumnWidth].
  ///
  /// The same information is also contained in the [columnDefinitions],
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_row.dart
> +  /// Used to highlight every other row through [hasEvenRowHighlight].
```suggestion
  /// This is the index of this row in the table.
  ///
  /// Used to highlight every other row through [hasEvenRowHighlight].
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_selection.dart
> +/// The selection state of a [MacosTable].
```suggestion
/// {@template macosTableSelection}
/// The selection state of a [MacosTable].
/// {@endtemplate}
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_selection.dart
> +  // TODO: Implement selecting multiple rows.
```suggestion
  /// {@macro macosTableSelection}
  // TODO: Implement selecting multiple rows.
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_selection.dart
> +/// Includes the old and the new selection.
```suggestion
/// Represents a change of a [MacosTable] selection.
///
/// Includes the old and the new selection.
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_selection.dart
> +/// Used to figure out whether a row should rebuild after a selection change.
```suggestion
/// {@template macosTableSelectionChange}
/// Used to figure out whether a row should rebuild after a selection change.
/// {@endtemplate}
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_selection.dart
> +  const MacosTableSelectionChange(
```suggestion
  /// {@macro macosTableSelectionChange}
  const MacosTableSelectionChange(
```

2023-01-24 09:04 UTC, GroovinChip commented on lib/src/layout/table/macos_table_view.dart
> +    /// Every Table widget needs this, so it is created once and cached here.
```suggestion
    /// A map from column index to its [TableColumnWidth].
    ///
    /// Every Table widget needs this, so it is created once and cached here.
```

2023-01-24 09:09 UTC, GroovinChip requested changes
One more thing - can you please post a screenshot of the table in dark mode? I want to make sure that it looks good with dark theme.

Also can you please run `flutter format` on `macos_table_datasource.dart`

2023-01-24 11:02 UTC, Yetispapa commented
@pithuene looking forward for the merge! Can you maybe give me an example, how the ordering actually work?

It seems, when I change the datasource like so:

```

StreamBuilder(
          stream: widget.bloc.items,
          initialData: widget.bloc.items.value,
          builder: (BuildContext context, snapshot) {

....

    changeOrder: (order) {
      // this will update the StreamBuilder
      widget.bloc.changeOrder(order.direction.name);
      return true;
    },
```

The ordering gets messed up somehow. Can you help me here out. Thanks

2023-01-24 13:02 UTC, pithuene commented
I can take a look @Yetispapa but I would need more context, its hard to tell much just from the code you've shown.
You need to implement the ordering yourself (which you probably did in `bloc.changeOrder`, but I can't see).
Also I am not sure why you wrapped the table in a `StreamBuilder`, you should call `dataChanged` on the data source after the data has changed and let the table do the rebuilding internally.

2023-01-25 10:49 UTC, Yetispapa commented
@pithuene, thanks for the quick repsonse. Alright. Let me check it again.

2023-02-04 21:53 UTC, GroovinChip commented
@pithuene anything new to report on this?

2023-02-04 23:03 UTC, pithuene commented
@GroovinChip not yet. I've been too busy the last few weeks, might find the time next week though.

2023-02-04 23:04 UTC, GroovinChip commented
No problem my dude, take your time. Your life comes first :)

2024-09-28 21:11 UTC, romanr commented
PR gonna be 2 years in couple e months 🍾

2024-09-29 09:16 UTC, pithuene commented
Yeah, sorry about that, but I won't be able to finish it. If anyone wants to use my code and take it from here, feel free. But I'm closing the PR for now.

2024-09-29 09:16 UTC, closed without merging