feat: implement MacosDisclosureButton
macosui/macos_ui pull request #326
Opened 2023-01-09 13:19 UTC by Umar1312

## Pre-launch Checklist

- [ x ] I have run `dartfmt` on all changed files 
- [ x ] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [ ] I have added/updated relevant documentation 
- [ x ] I have run "optimize/organize imports" on all changed files
- [ x ] I have addressed all analyzer warnings as best I could

2023-01-13 19:24 UTC, GroovinChip commented
Hi @Umar1312, thanks for opening this PR! 

Please address the failing check, and then I can review.

2023-01-14 09:54 UTC, Umar1312 commented
> Hi @Umar1312, thanks for opening this PR!
> 
> Please address the failing check, and then I can review.

Addressed. Please check. 

Thanks!

2023-01-14 14:32 UTC, GroovinChip commented
@Umar1312 The Flutter analysis check is still failing, looks like your test file.

2023-01-14 14:35 UTC, GroovinChip commented
Also, if you could please upload a gif of the widget in action, I'd really appreciate it. I don't generally have the time to pull PR branches and manually run the example to test the new code, so gifs are essential to my reviews.

2023-01-14 19:02 UTC, Umar1312 commented
Addressed. Also PFA the gif of widget in action. 

Thanks!

![DisclosureButtonGIf](https://user-images.githubusercontent.com/35866694/212491674-0bd8ea11-c23e-4fc5-b53f-58eebf6254a6.gif)

2023-01-24 12:28 UTC, GroovinChip approved these changes
OK so I've done a more thorough review and there are some fundamental changes that should be made:

- The disclosure control that is used for showing and hiding information and functionality associated with a view or list of items is called a [Disclosure triangle](https://developer.apple.com/design/human-interface-guidelines/components/layout-and-organization/disclosure-controls#disclosure-triangles). The widget should be updated to reflect this.
- The disclosure control that is used for showing and hiding functionality associated with a specific control is called a [Disclosure button](https://developer.apple.com/design/human-interface-guidelines/components/layout-and-organization/disclosure-controls#disclosure-buttons). This one looks like what you've made, but the chevron points **down**.

I think for both of these modes, the widget should operate in a similar manner to Flutter's [ExpansionTile](https://api.flutter.dev/flutter/material/ExpansionTile-class.html), which can show/hide other widgets.

2023-01-24 12:28 UTC, GroovinChip commented on lib/src/buttons/disclosure_button.dart
> +                              : const Color(0xffE5E5E5)
```suggestion
                              ? const MacosColor(0xff3C383C)
                              : const MacosColor(0xffE5E5E5)
```

2023-01-26 07:52 UTC, GroovinChip requested changes
Thought I'd done this as part of my previous comment but I guess not. Please see that and make the required changes. Thanks!

2023-01-28 19:55 UTC, Umar1312 commented
@GroovinChip Thanks for reviewing. I'm not quite sure on what changes I should make for this.

1. Going through the Apple's Docs, what we are trying to to implement is `NSBezelStyleRoundedDisclosure`. The actual  implementation of the hide/show part should be the responsibility of the user as is the case for Apple's own implementation.

2. If you still want to incorporate the show/hide functionality then we should probably not view it as a button widget, as it's scope has now changed considerably. 


Let me know what you think about this.

2023-01-30 01:51 UTC, GroovinChip commented
@Umar1312 I'll think about this and get back to you, thanks.

2023-02-03 17:34 UTC, GroovinChip commented
OK @Umar1312 we can keep things as they are. I'll review now.

2023-02-03 18:27 UTC, Umar1312 commented
@GroovinChip Thanks, updated.

2023-02-04 02:04 UTC, GroovinChip commented
@Umar1312 I actually just overhauled `MacosScrollBar` which allows the return of the `ScrollController` to `ContentArea`. If you want I can land that first, or you can open a new PR afterwards. What would you like to do?

2023-02-04 02:08 UTC, GroovinChip requested changes
Just some minor documentation requests :)

2023-02-04 02:08 UTC, GroovinChip commented on lib/src/buttons/disclosure_button.dart
> +  final VoidCallback? onPressed;
Document this please

2023-02-04 02:08 UTC, GroovinChip commented on lib/src/buttons/disclosure_button.dart
> +  final bool isPressed;
Document this please

2023-02-04 02:08 UTC, GroovinChip commented on lib/src/buttons/disclosure_button.dart
> +  /// enable a button, set its [onPressed] property to a non-null value.
```suggestion
  /// Whether the button is enabled or disabled. Buttons are disabled by default. 
  ///
  /// To enable a button, set its [onPressed] property to a non-null value.
```

2023-02-04 08:36 UTC, Umar1312 commented
@GroovinChip Updated.

2023-02-04 21:44 UTC, GroovinChip approved these changes
LGTM 🎉

2023-02-04 21:44 UTC, merged