Fix: use the `sidebard` and `endSidebar` key parameter
macosui/macos_ui pull request #400
Opened 2023-03-29 16:42 UTC by Maksimka101

- pass sidebar key to the sidebar root widget (`AnimatedPositioned`)
- create a new sidebar `ScrollController` when the key is change

### Why?
It wasn't possible to properly implement a tab bar in sidebar. Because when I have a few tabs and on each tab I have a scroll view two scrolls are connected to one controller when I switch between tabs 

## Pre-launch Checklist

- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [x] I have added/updated relevant documentation 
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could

2023-03-31 15:18 UTC, GroovinChip commented
@Maksimka101 Is there an open issue for this? Can you please upload a gif or screenshots demonstrating your changes?

2023-03-31 19:37 UTC, Maksimka101 commented
No, there is no issues for this.

Video with fix:

https://user-images.githubusercontent.com/35934153/229212647-629a4353-e0fd-41ef-abd0-47f993625d3a.mov

Video without fix:

https://user-images.githubusercontent.com/35934153/229212946-6f76722b-99a4-4c4e-93d8-c0d181601777.mov

<details>
<summary>Error stacktrace:</summary>

═══════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building LayoutBuilder:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
scroll_controller.dart:1
Failed assertion: line 108 pos 12: '_positions.length == 1'

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
MacosWindow
desktop_home_tab_body_builder.dart:12
When the exception was thrown, this was the stack
#2      ScrollController.position
scroll_controller.dart:108
#3      ScrollController.offset
scroll_controller.dart:115
#4      _MacosWindowState.build.<anonymous closure>
window.dart:221
#5      _LayoutBuilderElement._layout.layoutCallback
layout_builder.dart:119
#6      BuildOwner.buildScope
framework.dart:2682
#7      _LayoutBuilderElement._layout
layout_builder.dart:153
#8      RenderObject.invokeLayoutCallback.<anonymous closure>
object.dart:2300
#9      PipelineOwner._enableMutationsToDirtySubtrees
object.dart:1056
#10     RenderObject.invokeLayoutCallback
object.dart:2300
#11     RenderConstrainedLayoutBuilder.rebuildIfNecessary
layout_builder.dart:228
#12     _RenderLayoutBuilder.performLayout
layout_builder.dart:313
#13     RenderObject.layout
object.dart:2189
#14     RenderBox.layout
box.dart:2430
#15     ChildLayoutHelper.layoutChild
layout_helper.dart:56
#16     RenderStack._computeSize
stack.dart:595
#17     RenderStack.performLayout
stack.dart:622
#18     RenderObject._layoutWithoutResize
object.dart:2027
#19     PipelineOwner.flushLayout
object.dart:1020
#20     RendererBinding.drawFrame
binding.dart:516
#21     WidgetsBinding.drawFrame
binding.dart:865
#22     RendererBinding._handlePersistentFrameCallback
binding.dart:381
#23     SchedulerBinding._invokeFrameCallback
binding.dart:1289
#24     SchedulerBinding.handleDrawFrame
binding.dart:1218
#25     SchedulerBinding._handleDrawFrame
binding.dart:1076
#29     _invoke (dart:ui/hooks.dart:147:10)

</details>

2023-04-01 00:03 UTC, GroovinChip commented
Are you using a CupertinoTabView for that?

2023-04-02 06:24 UTC, Maksimka101 commented
I use stack. The problem is in the scroll controller. When I change a tab, I can't change scroll controller so I face this issue

2023-04-06 10:16 UTC, Maksimka101 commented
@GroovinChip hey. Do I need to do anything else to merge it?🙂

2023-04-06 15:38 UTC, GroovinChip requested changes
Also please run `flutter pub get` in order to update the lockfiles.

2023-04-06 15:38 UTC, GroovinChip commented on CHANGELOG.md
> +* Fixed a bug where the `Sidebar.key` parameter wasn't used so it was impossible to properly implement a tab bar in the sidebar
```suggestion
* Fixed a bug where the `Sidebar.key` parameter wasn't used, which caused certain layouts to be unachievable.
```

2023-04-06 15:38 UTC, GroovinChip commented on CHANGELOG.md
> +## [1.12.4]
```suggestion
## [1.12.5]
```

2023-04-06 15:38 UTC, GroovinChip commented on pubspec.yaml
> +version: 1.12.4
```suggestion
version: 1.12.5
```

2023-04-06 18:29 UTC, GroovinChip approved these changes

2023-04-06 18:30 UTC, merged