123669 handle invalid dates
macosui/macos_ui pull request #401
Opened 2023-03-29 17:10 UTC by eliasyishak

Refers to issue: https://github.com/flutter/flutter/issues/123669

My detailed explanation is in this comment: https://github.com/flutter/flutter/issues/123669#issuecomment-1488908243

## Pre-launch Checklist

- [ ] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [ ] I have added/updated relevant documentation 
- [ ] I have run "optimize/organize imports" on all changed files
- [ ] I have addressed all analyzer warnings as best I could

2023-03-29 17:17 UTC, eliasyishak commented
@GroovinChip let me know if I did this correctly for the PR. I was not sure if I should be merging into dev or customer_testing.

Also for the fix, it was even simpler to just set the `_selectedDay` variable to be 1 so it always points to the beginning of the month. Let me know if this is an okay assumption to make.

2023-03-31 15:05 UTC, GroovinChip commented
@eliasyishak Thanks for submitting this fix. You're correct to target the `dev` branch. I'll review this now.

2023-03-31 15:11 UTC, eliasyishak commented
> @eliasyishak Thanks for submitting this fix. You're correct to target the `dev` branch. I'll review this now.

Oh but it seems like I targeted `customer_testing`, should I point it to `dev` instead?

2023-03-31 15:13 UTC, GroovinChip commented
> > @eliasyishak Thanks for submitting this fix. You're correct to target the `dev` branch. I'll review this now.
> 
> Oh but it seems like I targeted `customer_testing`, should I point it to `dev` instead?

Ah yes. Please target dev.

2023-03-31 15:15 UTC, GroovinChip requested changes
Looks fine, please just update the version in `pubspec.yaml` to match your changelog entry.

2023-03-31 15:15 UTC, GroovinChip commented on CHANGELOG.md
> +* Default the `_selectedDay` state variable to be 1 when selecting the previous/next month from widget to ensure new date is valid for `_formatAsDateTime()` method
```suggestion
* Default the `_selectedDay` state variable to be 1 when selecting the previous/next month from widget to ensure new date is valid for `_formatAsDateTime()` method (https://github.com/flutter/flutter/issues/123669 & https://github.com/macosui/macos_ui/pull/401)
```

2023-03-31 15:17 UTC, GroovinChip commented
@eliasyishak Which Flutter channel are you on? see https://github.com/macosui/macos_ui/blob/dev/CONTRIBUTING.md#branch-structure

2023-03-31 15:21 UTC, eliasyishak commented
Is it better for me to make the change on a fork of `dev` instead? I was getting a lot of errors when I forked dev in the tests initially so i used `customer_testing` instead.

2023-03-31 15:23 UTC, GroovinChip commented
Yes, as explained in `CONTRIBUTING.md`, `macos_ui` is developed on Flutter's stable channel. Only the `customer_testing` branch is on `master`. You likely experienced those errors because you are not on Flutter's stable channel.

2023-03-31 15:27 UTC, eliasyishak commented
Closing to move to another PR based on `dev`

2023-03-31 15:27 UTC, closed without merging