feat: Added support for `startWeekOnMonday` to `MacosDatePicker`
macosui/macos_ui pull request #414
Opened 2023-04-16 13:05 UTC by rklos

This is the first step in fulfilling all requests from https://github.com/macosui/macos_ui/issues/369.
I've added an optional parameter `startWeekOnMonday` which allows to render a calendar with Monday as a first day of the week. 

## Pre-launch Checklist

- [X] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [X] I have added/updated relevant documentation 
- [X] I have run "optimize/organize imports" on all changed files
- [X] I have addressed all analyzer warnings as best I could

2023-04-18 21:15 UTC, rklos commented
I've added an additional test that checks if `startWeekOnMonday` is still necessary. This test will fail on `customer_testing` branch when Flutter has fixed `firstDayOfWeekIndex`.

2023-07-03 18:36 UTC, GroovinChip requested changes
Thanks for your contribution, @rklos! Please merge in the latest from `dev` (you'll need to bump the beta version in the `pubspec` and changelog) and make the requested changes. Thanks!

2023-07-03 18:36 UTC, GroovinChip commented on lib/src/selectors/date_picker.dart
> +  final bool? startWeekOnMonday;
Please add some documentation describing this property's purpose. It may be intuitive for some, but for others it may not be.

2023-07-03 18:36 UTC, GroovinChip commented on lib/src/selectors/date_picker.dart
> +  // or Mo, Tu, We, Th, Fr, Sa, Su depending on the value of startWeekOnMonday
```suggestion
  // or Mo, Tu, We, Th, Fr, Sa, Su depending on the value of [startWeekOnMonday]
```

2023-07-03 20:18 UTC, rklos commented
Done @GroovinChip

2023-07-03 21:41 UTC, GroovinChip requested changes
Some minor grammatical changes needed

2023-07-03 21:41 UTC, GroovinChip commented on lib/src/selectors/date_picker.dart
> +  /// Allows to change the order of day headers in the graphical Date Picker
```suggestion
  /// Allows for changing the order of day headers in the graphical Date Picker
```

2023-07-03 21:41 UTC, GroovinChip commented on lib/src/selectors/date_picker.dart
> +  /// Defaults to `false`
```suggestion
  /// Defaults to `false`.
```

2023-07-03 21:41 UTC, GroovinChip commented on lib/src/selectors/date_picker.dart
> +  /// to Mo, Tu, We, Th, Fr, Sa, Su
```suggestion
  /// to Mo, Tu, We, Th, Fr, Sa, Su.
```

2023-07-04 13:45 UTC, GroovinChip requested changes

2023-07-04 13:45 UTC, GroovinChip commented on lib/src/selectors/date_picker.dart
> +  final bool? startWeekOnMonday;
```suggestion
  /// Allows for changing the order of day headers in the graphical Date Picker
  /// to Mo, Tu, We, Th, Fr, Sa, Su.
  /// 
  /// This is useful for internationalization purposes, as many countries begin their weeks on Mondays.
  /// 
  /// Defaults to `false`.
  final bool? startWeekOnMonday;
```

2023-07-04 13:45 UTC, GroovinChip approved these changes

2023-07-04 13:45 UTC, GroovinChip commented
LGTM. Waiting on checks.

2023-07-04 13:48 UTC, merged