feat: Added support for `dateFormat` to `MacosDatePicker`
macosui/macos_ui pull request #415
Opened 2023-04-16 14:28 UTC by rklos

This is another feature from https://github.com/macosui/macos_ui/issues/369.
I've added an optional parameter `dateFormat` which allows to change the way dates are displayed in the textual interface.

## Pre-launch Checklist

- [X] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [X] I have added/updated relevant documentation 
- [X] I have run "optimize/organize imports" on all changed files
- [X] I have addressed all analyzer warnings as best I could

2023-07-03 18:38 UTC, GroovinChip requested changes
Looking good, just merge in the latest from `dev`, adjust the beta version where appropriate, and make the requested change. Thanks!

2023-07-03 18:38 UTC, GroovinChip commented on lib/src/selectors/date_picker.dart
> +  final String? dateFormat;
Please add some documentation for this.

2023-07-03 19:47 UTC, rklos commented on lib/src/selectors/date_picker.dart
> +  final String? dateFormat;
Done

2023-07-03 21:44 UTC, GroovinChip requested changes
Just a minor dartdoc formatting change needed, then we're good to go.

2023-07-03 21:44 UTC, GroovinChip commented on lib/src/selectors/date_picker.dart
> +  /// The following tokens are supported (case-insensitive):
```suggestion
  /// Changes the way dates are displayed in the textual interface.
  /// 
  /// The following tokens are supported (case-insensitive):
```

2023-07-04 13:47 UTC, GroovinChip approved these changes
LGTM. Waiting on checks and #414.

2023-07-04 13:51 UTC, merged