Fix `MacosPulldownMenuItem.onTap` doesn't open alert dialog
macosui/macos_ui pull request #520
Opened 2024-10-03 21:43 UTC by TahaTesser

fixes [MacosPulldownMenuItem onTap doesnt call showMacosAlertDialog ](https://github.com/macosui/macos_ui/issues/516)

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/cupertino.dart';
import 'package:macos_ui/macos_ui.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MacosApp(
      debugShowCheckedModeBanner: false,
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return MacosScaffold(
      toolBar: ToolBar(
        title: const Text('macos_ui'),
        actions: [
          ToolBarPullDownButton(
            label: 'Actions',
            icon: CupertinoIcons.ellipsis_circle,
            tooltipMessage: 'Perform tasks with the selected items',
            items: [
              MacosPulldownMenuItem(
                label: 'New Folder',
                title: const Text('New Folder'),
                onTap: () => showMacosAlertDialog(
                  context: context,
                  builder: (context) => MacosAlertDialog(
                    appIcon: const FlutterLogo(size: 64),
                    title: const Text('Title'),
                    message: const Text('Message'),
                    //horizontalActions: false,
                    primaryButton: PushButton(
                      controlSize: ControlSize.large,
                      onPressed: Navigator.of(context).pop,
                      child: const Text('Label'),
                    ),
                  ),
                ),
              ),
              MacosPulldownMenuItem(
                label: 'Open',
                title: const Text('Open'),
                onTap: () => debugPrint('Opening...'),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
```

</details>

### Preview 

<img width="859" alt="Screenshot 2024-10-04 at 00 40 39" src="https://github.com/user-attachments/assets/aaaed57d-5e8d-4c12-9c99-b24d95e43c4e">

## Pre-launch Checklist

- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [ ] I have added/updated relevant documentation 
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could

2024-10-03 22:04 UTC, GroovinChip requested changes
Thanks for the PR @TahaTesser !!! Just one small change request and then we are good to go

2024-10-03 22:04 UTC, GroovinChip commented on lib/src/buttons/pulldown_button.dart
>        Navigator.pop(context);
Can we make this `.of(context).pop()` please?

2024-10-03 22:13 UTC, GroovinChip approved these changes
LGTM! 🚀

2024-10-03 22:14 UTC, GroovinChip commented
Just gonna run the checks manually since you're a first time contributor

2024-10-04 12:01 UTC, GroovinChip commented
Looks like we've got some failing tests

2024-10-04 15:38 UTC, TahaTesser commented
>  Looks like we've got some failing tests

For some reason test passes locally with FlutterLogo but not in the CI so i just replaced it.

2024-10-05 16:30 UTC, merged