Implemente mouse cursors
macosui/macos_ui pull request #67
Opened 2021-05-09 22:50 UTC by bdlukaa

Implemented mouse cursors for checkbox, help button, push button, radio button and text fields' clear button

Closes #63 

## Pre-launch Checklist

- [x] I have run `dartfmt` on all changed files
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could
- [ ] I have added/updated relevant documentation
- [ ] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes
- [ ] I have run `flutter pub publish --dry-run` and addressed any warnings

2021-05-09 23:12 UTC, bdlukaa commented
Text field should change the mouse cursor as well.

2021-05-10 00:06 UTC, GroovinChip requested changes
LGTM but I think this warrants a small version bump and changelog entry

2021-05-10 00:20 UTC, bdlukaa commented
Done

2021-05-10 00:26 UTC, GroovinChip commented
Maybe it's because I'm on mobile but I don't see the change. I'll be able to get on the computer in a few minutes though (hopefully)

2021-05-10 00:27 UTC, bdlukaa commented
Ooh sorry I forgot to push it lol. Done now

2021-05-10 00:30 UTC, GroovinChip approved these changes
LGTM

2021-05-10 00:30 UTC, merged