Implement Label
macosui/macos_ui pull request #93
Opened 2021-05-14 22:51 UTC by bdlukaa

Implemented Label.

![Label Showcase](https://user-images.githubusercontent.com/45696119/118338836-86fe6580-b4ed-11eb-8312-ab2b031a73cb.png)

See #61 
Closes #87 

## Pre-launch Checklist

- [x] I have run `dartfmt` on all changed files
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could
- [x] I have added/updated relevant documentation
- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes
- [ ] I have run `flutter pub publish --dry-run` and addressed any warnings

2021-05-14 23:53 UTC, GroovinChip approved these changes
LGTM

2021-05-14 23:54 UTC, GroovinChip requested changes
Actually - if you updated the version in the changelog, update it in the pubspec.yaml too

2021-05-14 23:55 UTC, bdlukaa commented
@GroovinChip It is already 1.0.1

2021-05-14 23:55 UTC, bdlukaa commented
I changed it in #82

2021-05-14 23:56 UTC, GroovinChip commented
@bdlukaa you're saying it's already 1.1.1? ![Screenshot_20210514-195632_GitHub.jpg](https://user-images.githubusercontent.com/4250470/118341800-84e8d680-b4ee-11eb-826e-1dc0d37581f6.jpg)

2021-05-14 23:57 UTC, bdlukaa commented
Yes, it is.

2021-05-14 23:58 UTC, bdlukaa commented
See https://github.com/GroovinChip/macos_ui/pull/91/files#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25R3

2021-05-15 00:08 UTC, GroovinChip commented
Okay.

2021-05-15 00:08 UTC, GroovinChip approved these changes
LGTM

2021-05-15 00:08 UTC, merged