Theme update
macosui/macos_ui pull request #94
Opened 2021-05-15 18:16 UTC by bdlukaa

Improved the theming api for better dev experience:

- [x] Move the `ThemeData` classes to its respective parent file (For example, `PushButtonThemeData` goes to `pushbutton.dart`)
- [x] Rename `DynamicColorX` to `MacosDynamicColor`, and fix color resolving
- [x] Properties in `MacosThemeData` and `Typography` can't be nullable
- [x] `MacosThemeData.lerp`, to give the possibility to have an `AnimatedMacosTheme` widget
- [x] Removed theme extension (`context.macosTheme`)

Closes #79 

## Pre-launch Checklist

- [x] I have run `dartfmt` on all changed files
- [ ] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could
- [x] I have added/updated relevant documentation
- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes
- [ ] I have run `flutter pub publish --dry-run` and addressed any warnings

2021-05-15 20:13 UTC, GroovinChip commented
Looks like pana analysis has failed, address the warnings there and then I'll review

2021-05-16 13:27 UTC, bdlukaa commented
@GroovinChip ready for review

2021-05-16 16:59 UTC, GroovinChip requested changes
I'm not finished reviewing this just all I could do at the moment

2021-05-16 16:59 UTC, GroovinChip commented on lib/src/styles/macos_theme.dart
> +/// of the entire app. Widget subtree's within an app can override the app's
Change to "**A** widget's subtree"

2021-05-16 16:59 UTC, GroovinChip commented on lib/src/styles/macos_theme.dart
> +  /// The [typography] [TextStyle] colors are black if the color scheme's
We don't use the `ColorScheme`, class so let's not use language that could confuse readers.

2021-05-16 16:59 UTC, GroovinChip commented on lib/src/styles/macos_theme.dart
> +  ///   * [MacosThemeData.light], which creates a light blue theme.
The blue color in this theme isn't different than the default dark theme so we should make sure not to use language that might imply a difference.

2021-05-17 03:24 UTC, GroovinChip commented
@bdlukaa Pana analysis is showing
```
INFO: Override `==` if overriding `hashCode`.
    ╷
234 │   int get hashCode {
    │           ^^^^^^^^
    ╵
```
Please address and then I will review.

2021-05-17 15:47 UTC, GroovinChip commented
Make sure to run organize imports on all changed files please

2021-05-17 17:09 UTC, bdlukaa commented
Done

2021-05-19 00:17 UTC, GroovinChip approved these changes
LGTM

2021-05-19 00:17 UTC, merged